export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
    alert: {
      edit: 'Edit',
      title: 'Confirm',
      delete: 'Delete',
      cancel: 'Cancel',
    },
  },
  navigation: {
    restaurants: 'Restaurants',
    createRestaurant: 'Create a restaurant',
    updateRestaurant: 'Update restaurant',
    restaurantDetail: 'Restaurant Detail',
    users: 'Users',
    editUser: 'Edit User',
    login: 'Login',
    register: 'Register',
    profile: 'Profile',
  },
  user: {
    role: 'Role',
    username: 'Username',
    noUserFound: 'No user found...',
    deleteMessage: 'Are you sure, you want to delete this user?',
  },
  review: {
    reviewTitle: 'Write a review',
    addReview: 'Add review',
    updateReview: 'Update review',
    enterText: 'Enter Text',
    titleValidation: 'Please enter comment.',
    dateOfVisit: 'Please select date of visit:',
    visitLabel: 'Visited on',
  },
  restaurant: {
    noRestaurant: 'No restaurant found...',
    noReview: 'No review so far...',
    reply: 'Reply',
    adminAlert: {
      title: 'Edit or delete?',
      messageComment: 'You can either edit or delete this comment',
      messageReview: 'You can either edit or delete this review',
    },
    deleteMessage: 'Are you sure, you want to delete this restaurant?',
    detail: {
      topRated: 'Highest Rated Review:',
      lowRated: 'Lowest Rated Review:',
      latestReviews: 'Latest Reviews:',
    },
    filter: {
      title: 'Filter by:',
      noRating: 'No Rating',
      starRating: 'Star Rating',
    },
  },
  createRestaurant: {
    name: 'Name',
    description: 'Description',
    formError: 'Please enter',
    create: 'Create Restaurant',
    update: 'Update Restaurant',
    nameValidate: 'Restaurant Name should be in between 2-50 characters in length',
  },
  commentBox: {
    writeComment: 'Write a comment...',
    cancel: 'Cancel',
    submit: 'Submit',
  },
  authentication: {
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'Username',
    password: 'Password',
    selectRole: 'Please select your role',
    validations: {
      firstName: 'First Name should be in between 2-50 characters in length',
      lastName: 'Last Name should be in between 2-50 characters in length',
      username: 'Username should be in between 2-20 characters in length',
      shortPassword: 'Password should be atleast 6 characters long',
      longPassword: 'Password is too long. Please use less than 100 characters.',
    },
    userRoles: {
      user: 'User',
      admin: 'Admin',
      owner: 'Owner',
    },
    formError: 'Please enter',
  },
  login: {
    button: 'Login',
    invalidCredentials: 'Invalid Username/Password',
    newUser: 'New user? Register Here',
  },
  register: {
    button: 'Register',
    backToLogin: 'Back to login',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This is profile screen.',
  },
};
